### ISSUE TITLE
File or directory is not found

### ISSUE THREAD

**Issue by aminonar21** [nbebaw/cpumanagergui#1]
![Screenshot_20191125_092935](https://user-images.githubusercontent.com/58165989/69525208-e8342100-0f67-11ea-8c9a-1894743309ec.png)
I have got this message when I tried to open the App.. Please help

**Comment by nbebaw** [comment]
I am sorry for that. Did you tried to open this Program under VM (Virtual Machine)?. If yes, then this is a normal failure message because I made this program to work only on a real Machine. This Program modifies a file in the Kernel and this File will not be available if you are using VM.

**Comment by aminonar21** [comment]
Yes. I tried the Program under a VM to test it but I will try it under my real Machine. Thnx for your reply

**Comment by nbebaw** [comment]
Perfect. Please test it again and give me your Feedback.

**Comment by aminonar21** [comment]
It works now without any problem. Thank you for making such a good Program. I tested it if this program consuming a lot of Battery While it is open and the result is: NO. Perfect. Thnx man!

**Comment by nbebaw** [comment]
I am glad to hear that :) .. Thank you very much for your feedback. 
Please close this issue if everything is alright now.
